services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - ENV=production
    ports:
      - "8000:8000"
    restart: on-failure
